export const ImagePath = {
    logo: require('../Assets/Images/logo.png'),
    wellcome_logo: require('../Assets/Images/wellcome_logo.png'),
    shape: require('../Assets/Images/shape.png'),
    eye_on: require('../Assets/Images/eye_on.png'),
    eye_off: require('../Assets/Images/eye_off.png'),
    dp: require('../Assets/Images/dp.png'),
    menu: require('../Assets/Images/menu.png'),
    home: require('../Assets/Images/home.png'),
    back: require('../Assets/Images/back.png'),
    upload: require('../Assets/Images/upload.png'),
    add: require('../Assets/Images/add.png'),
    logout: require('../Assets/Images/logout.png'),
    delete: require('../Assets/Images/delete.png'),
    edit: require('../Assets/Images/edit.png'),
    upload_image: require('../Assets/Images/upload_image.png'),
    add_blank: require('../Assets/Images/add_blank.png'),
    close: require('../Assets/Images/close.png'),
    arrow_down: require('../Assets/Images/arrow_down.png'),
    arrow_up: require('../Assets/Images/arrow_up.png'),
    search: require('../Assets/Images/search.png'),
    sort: require('../Assets/Images/sort.png'),
    date: require('../Assets/Images/date.png'),
    camera: require('../Assets/Images/camera.png'),
    req_id: require('../Assets/Images/req_id.png'),
    location: require('../Assets/Images/location.png'),
    factory: require("../Assets/Images/factory.png"),
    car: require('../Assets/Images/car.png'),
    info: require('../Assets/Images/info.png'),
    truck: require('../Assets/Images/truck.png'),
    slip: require('../Assets/Images/slip.png'),
    cloud_upload: require('../Assets/Images/cloud_upload.png'),
    edit_profile: require('../Assets/Images/edit_profile.png'),
    lock: require('../Assets/Images/lock.png'),
    request: require('../Assets/Images/request.png'),
    pending: require('../Assets/Images/pending.png'),
    complete: require('../Assets/Images/complete.png'),
    reject: require('../Assets/Images/reject.png'),
    success_animation: require('../Assets/Images/success_animation.json'),
    bell: require('../Assets/Images/bell.png'),
    pdf_upload: require('../Assets/Images/pdf_upload.png'),
    close_round: require('../Assets/Images/close_round.png'),
    delete_acnt: require('../Assets/Images/delete_acnt.png'),
    terms_condition:require('../Assets/Images/terms_condition.png'),
    privacy_policy:require('../Assets/Images/privacy_policy.png')
}